import { Ppc } from '.'

let ppc

beforeEach(async () => {
  ppc = await Ppc.create({ date: 'test', portfolio: 'test', currency: 'test', campaign: 'test', adGroup: 'test', targeting: 'test', matchType: 'test', impressions: 'test', clicks: 'test', ctr: 'test', cpc: 'test', spend: 'test', tacos: 'test', troas: 'test', 7dTotalSales: 'test', 7dTotalOrders: 'test', 7dTotalUnits: 'test', 7dConversion: 'test', 7dAdvertisedSkuUnits: 'test', 7dOtherSkuUnits: 'test', 7dAdvertisedSkuSales: 'test', 7dOtherSkuSales: 'test' })
})

describe('view', () => {
  it('returns simple view', () => {
    const view = ppc.view()
    expect(typeof view).toBe('object')
    expect(view.id).toBe(ppc.id)
    expect(view.date).toBe(ppc.date)
    expect(view.portfolio).toBe(ppc.portfolio)
    expect(view.currency).toBe(ppc.currency)
    expect(view.campaign).toBe(ppc.campaign)
    expect(view.adGroup).toBe(ppc.adGroup)
    expect(view.targeting).toBe(ppc.targeting)
    expect(view.matchType).toBe(ppc.matchType)
    expect(view.impressions).toBe(ppc.impressions)
    expect(view.clicks).toBe(ppc.clicks)
    expect(view.ctr).toBe(ppc.ctr)
    expect(view.cpc).toBe(ppc.cpc)
    expect(view.spend).toBe(ppc.spend)
    expect(view.tacos).toBe(ppc.tacos)
    expect(view.troas).toBe(ppc.troas)
    expect(view.7dTotalSales).toBe(ppc.7dTotalSales)
    expect(view.7dTotalOrders).toBe(ppc.7dTotalOrders)
    expect(view.7dTotalUnits).toBe(ppc.7dTotalUnits)
    expect(view.7dConversion).toBe(ppc.7dConversion)
    expect(view.7dAdvertisedSkuUnits).toBe(ppc.7dAdvertisedSkuUnits)
    expect(view.7dOtherSkuUnits).toBe(ppc.7dOtherSkuUnits)
    expect(view.7dAdvertisedSkuSales).toBe(ppc.7dAdvertisedSkuSales)
    expect(view.7dOtherSkuSales).toBe(ppc.7dOtherSkuSales)
    expect(view.createdAt).toBeTruthy()
    expect(view.updatedAt).toBeTruthy()
  })

  it('returns full view', () => {
    const view = ppc.view(true)
    expect(typeof view).toBe('object')
    expect(view.id).toBe(ppc.id)
    expect(view.date).toBe(ppc.date)
    expect(view.portfolio).toBe(ppc.portfolio)
    expect(view.currency).toBe(ppc.currency)
    expect(view.campaign).toBe(ppc.campaign)
    expect(view.adGroup).toBe(ppc.adGroup)
    expect(view.targeting).toBe(ppc.targeting)
    expect(view.matchType).toBe(ppc.matchType)
    expect(view.impressions).toBe(ppc.impressions)
    expect(view.clicks).toBe(ppc.clicks)
    expect(view.ctr).toBe(ppc.ctr)
    expect(view.cpc).toBe(ppc.cpc)
    expect(view.spend).toBe(ppc.spend)
    expect(view.tacos).toBe(ppc.tacos)
    expect(view.troas).toBe(ppc.troas)
    expect(view.7dTotalSales).toBe(ppc.7dTotalSales)
    expect(view.7dTotalOrders).toBe(ppc.7dTotalOrders)
    expect(view.7dTotalUnits).toBe(ppc.7dTotalUnits)
    expect(view.7dConversion).toBe(ppc.7dConversion)
    expect(view.7dAdvertisedSkuUnits).toBe(ppc.7dAdvertisedSkuUnits)
    expect(view.7dOtherSkuUnits).toBe(ppc.7dOtherSkuUnits)
    expect(view.7dAdvertisedSkuSales).toBe(ppc.7dAdvertisedSkuSales)
    expect(view.7dOtherSkuSales).toBe(ppc.7dOtherSkuSales)
    expect(view.createdAt).toBeTruthy()
    expect(view.updatedAt).toBeTruthy()
  })
})
